version: "3.8"

services: 
  arangodb:
    image: arangodb:latest
    environment: 
      ARANGO_ROOT_PASSWORD: password
    ports:
      - "8529:8529"
    container_name: arangodb
    volumes:
      - arangodb_data_container:/var/lib/arangodb3
      - arangodb_apps_data_container:/var/lib/arangodb3-apps

  app:
    build: .
    container_name: app
    
volumes:
  arangodb_data_container:
  arangodb_apps_data_container:
