version: "3.8"
services: 
  arangodb:
    image: arangodb:latest
    environment: 
      ARANGO_ROOT_PASSWORD: password
    ports:
      - "8529:8529"
    container_name: arangodb

  app:
    build: .
    depends_on:
      - arangodb
    container_name: app
