apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
        app: cliente
  template:
    metadata:
      labels:
        app: cliente
    spec:
      containers:
      - name: mi-cliente
        image: urkazio/app
