apiVersion: apps/v1
kind: Deployment
metadata:
  name: arangodb-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      bd: arangodb
  template:
    metadata:
      labels:
        bd: arangodb
    spec:
      volumes:  
      - name: volumen-arangodb
        persistentVolumeClaim: 
          claimName: mi-reclamacion
      containers:
      - name: mi-arangodb
        image: arangodb:latest
        ports:
        - containerPort: 8529
        env:
        - name: ARANGO_ROOT_PASSWORD
          value: "password"
        volumeMounts: 
        - name: volumen-arangodb
          mountPath: /var/lib/arangodb3
