apiVersion: apps/v1
kind: Deployment
metadata:
  name: arangodb-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      bd: arangodb
  template:
    metadata:
      labels:
        bd: arangodb
    spec:
      containers:
      - name: mi-arangodb
        image: arangodb:latest
        ports:
        - containerPort: 8529
