version: "3.8"
services:
  arangodb:
    image: arangodb:latest
    environment:
      ARANGO_ROOT_PASSWORD: password
    ports:
      - "8529:8529"
    container_name: arangodb
  app:
    build: .
    container_name: app
    volumes:
    - /home/urko/proyecto/3app/code:/code
  apache:
    image: httpd:latest
    container_name: my-apache-app
    ports:
    - '8080:80'
    volumes:
    - ./code:/usr/local/apache2/htdocs
